# Generated by Django 5.1.6 on 2025-02-27 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='job_title',
        ),
    ]
